name: Notify Discord on New Star

on:
  watch:
    types: [started]

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        uses: chase-roohms/discord-notify@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "Cursed Bundles"  # Write your custom name here
          content: "Damn, **${{ github.event.sender.login }}** just starred Wantechfan/mindustry-cursed-bundles!"
