name: Discord Custom Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom Discord message
        uses: chase-roohms/discord-notify@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "### ${{ github.actor }} pulled a request on ${{ github.repository }}!\nMessage: ${{ github.event.pull_request.title }}\nLink: ${{ github.event.pull_request.html_url }}\n-# <@1393198962101456949> someone pr-ed ${{ github.repository }}."
